---
- name: Create docker working directory
  file:
    path: "{{ minecraftoverviewer_docker_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ minecraftoverviewer_docker_compose_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload minecraftoverviewer service

- name: Create systemd unit file
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ minecraftoverviewer_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload minecraftoverviewer service

- name: Create systemd timer file
  template:
    src: systemd.timer.j2
    dest: "/etc/systemd/system/{{ minecraftoverviewer_service_name }}.timer"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart minecraftoverviewer timer

- name: Create render volume directory
  file:
    path: "{{ minecraftoverviewer_render_volume_directory }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: 0755

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable systemd service (if not started)
  service:
    name: "{{ minecraftoverviewer_service_name }}"
    enabled: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Enable/start systemd timer (if not started)
  service:
    name: "{{ minecraftoverviewer_service_name }}.timer"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
