---
- name: Install minecraftoverviewer
  include: install.yml
  when: >
    minecraftoverviewer_state is not defined
    or minecraftoverviewer_state == 'present'

- name: Remove minecraftoverviewer
  include: remove.yml
  when: >
    minecraftoverviewer_state is defined
    and minecraftoverviewer_state == 'absent'
