---
- name: Create docker working directory
  file:
    path: "{{ minecraftoverviewer_docker_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ minecraftoverviewer_docker_compose_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart minecraftoverviewer service

- name: Create systemd unit file
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ minecraftoverviewer_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart minecraftoverviewer service
