---
- name: Reload minecraftoverviewer service
  systemd:
    name: "{{ minecraftoverviewer_service_name }}"
    enabled: true
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Restart minecraftoverviewer timer
  systemd:
    name: "{{ minecraftoverviewer_service_name }}.timer"
    enabled: true
    state: restarted
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
