---
- name: Verify
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Should template docker-compose file
      slurp:
        src: /opt/my_minecraft_overviewer/docker/docker-compose.yml
      register: docker_compose_file
      failed_when:
        not docker_compose_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          ---
          version: "3.9"
          services:
            minecraft_overviewer:
              image: mide/minecraft-overviewer:2020-09
              container_name: my-minecraft-overviewer
              environment:
                MINECRAFT_VERSION: "1.16.5"
              volumes:
                - /srv/my_minecraftserver/minecraft-data:/home/minecraft/server/:ro
                - /srv/my_minecraft_overviewer/render:/home/minecraft/render/:rw

    - name: Should template systemd unit file
      slurp:
        src: /etc/systemd/system/minecraftoverviewer.service
      register: systemd_service_file
      failed_when:
        not systemd_service_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          [Install]
          WantedBy=multi-user.target

          [Unit]
          Description=minecraftoverview service
          After=docker.service
          Requires=docker.service

          [Service]
          ExecStartPre=-/usr/local/bin/docker-compose \
            --project-directory /opt/my_minecraft_overviewer/docker \
            --file /opt/my_minecraft_overviewer/docker/docker-compose.yml \
            --project-name minecraftoverview \
            down \
            --remove-orphans

          ExecStartPre=/usr/local/bin/docker-compose \
            --project-directory /opt/my_minecraft_overviewer/docker \
            --file /opt/my_minecraft_overviewer/docker/docker-compose.yml \
            --project-name minecraftoverview \
            pull

          ExecStart=/usr/local/bin/docker-compose \
            --project-directory /opt/my_minecraft_overviewer/docker \
            --file /opt/my_minecraft_overviewer/docker/docker-compose.yml \
            --project-name minecraftoverview \
            up

          ExecStop=/usr/local/bin/docker-compose \
            --project-directory /opt/my_minecraft_overviewer/docker \
            --file /opt/my_minecraft_overviewer/docker/docker-compose.yml \
            --project-name minecraftoverview \
            down \
            --remove-orphans

          Restart=no
          TimeoutSec=3600

    - name: Should template systemd timer file
      slurp:
        src: /etc/systemd/system/minecraftoverviewer.timer
      register: systemd_timer_file
      failed_when:
        not systemd_timer_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          [Unit]
          Description=Run minecraftoverview service

          [Timer]
          OnCalendar=hourly
          Persistent=true

          [Install]
          WantedBy=timers.target

    - name: Should create render volume
      stat:
        path: /srv/my_minecraft_overviewer/render
      register: render_volume_directory
      failed_when: not (
        render_volume_directory.stat.exists
        and render_volume_directory.stat.uid == 1000
        and render_volume_directory.stat.gid == 1000
        and render_volume_directory.stat.mode == '0755'
        )
