---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/all-parameters/requirements.yml
    force: true

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ansible-mcoverviewer-noble
    box: cloud-image/ubuntu-24.04
  - name: ansible-mcoverviewer-jammy
    box: cloud-image/ubuntu-22.04
  - name: ansible-mcoverviewer-focal
    box: cloud-image/ubuntu-20.04
  - name: ansible-mcoverviewer-bookworm
    box: cloud-image/debian-12
    groups:
      - debian
  - name: ansible-mcoverviewer-bullseye
    box: cloud-image/debian-11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../state-absent/prepare.yml
    converge: ../state-absent/converge.yml
    verify: ../state-absent/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
